server:
  port: 10081
spring:
  application:
    name: letao-eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18081/eureka
    fetch-registry: false
    register-with-eureka: false